//operations
let value = 3
let negvalue = -value
//console.log(negvalue);
//console.log(2+2); //addition
//console.log(2-2); //subtraction
//console.log(2*2); //multiplication
//console.log(2**2); //raise to power
//console.log(2/2); //division
//console.log(2%3); //remainder
// let str1 = 'hello'
// let str2 = "shubham"
// let str3 = str1+str2
// console.log(str3);
// console.log("1" + 2);
// console.log(1 + "2");
// console.log("1"+2+2);
// console.log(1+2+"2");
// console.log(+true);
// console.log(+"");
// let num1, num2, num3
// num1 = num2 = num3 = 2 + 2
// let gamecounter = 100
// gamecounter++;
// console.log(gamecounter);

//******************COMPARISION********* */
// console.log(2>1);
// console.log(2>=1);
// console.log(2<1);
// console.log(2<=1);
// console.log(2 == 1);
// console.log(2 != 1);
console.log("2">1);
console.log("02">1);

// console.log(null>0);
// console.log(null==0);
// console.log(null>=0);

// console.log(undefined ==0);
// console.log(undefined>0);
// console.log(undefined<0);
//this type of comparission may occur confusion during code

// ===(strict check)
// console.log("2" === 2);

















